### ISSUE TITLE
Důležité a obsáhlé topicy týkající se aukce

### ISSUE THREAD

**Issue by Sekiphp** [MineAuction/Spigot#1]
Linkování tajných informací

**Comment by DvnBthlo** [comment]
Nice

**Comment by DvnBthlo** [comment]
http://forum.majncraft.cz/threads/majncraft-2015-nether-metro-aukcia-iron-trapky.8987/#post-95942 - Na tomhle odkazu se mi zobrazi zmizni nikdo te tu nechce

**Comment by Sekiphp** [comment]
Všechny ty topicy jsem prošel a sepsal jsme specifikaci
