### ISSUE TITLE
WEB: Specifikace aukce

### ISSUE THREAD

**Issue by Sekiphp** [MineAuction/Spigot#2]
Nyní ve fázi návrhů!!! Sepsány nápady, které se mi zdály dobré ze všech topiců na fóru, co jsem našel atp.

1) Přihlašování do web-části pomocí minecraft loginu a hesla hashovaného ve sha256; heslo uživatel zadá pomocí příkazu například ve tvaru: /mineauction register heslo

2) Inventář hráče - přepínací karty/tlačítka/přepínače?, které postupně || dohromady (kombinace přepínačů) zobrazí hráčovy itemy, itemy, které aktuálně nabízí aj.

3) Seznam všech nabídek - sloupce: Název (obrázek), nick prodejce, cena za kus, cena celkem, procentuální porovnání cen, celkový počet, políčko pro nákup s tlačítkem

4) Filtrování podle názvu (LIKE %) ve všech sekcích s itemy

5) Všude defaultně zobrazovat stránku s max 25 nabídkami (možnost přepnutí na 50, 100, 500, všechny)

6.1) Poptávka - hledám itemy, které nikdo nenabízí a snažím se ostatní vybídnout ke koupi 
- ostatním hráčům se zobrazí kdo co poptává, aby mohli dávat nabídky (asi nezobrazit za kolik)
- automaticky když někdo přidá daný item, tak se zkontroluje jeslti ho někdo nepoptává a vyhraje poptávka s nejvyšší cenou
- po zadání poptávky se daný obnos zablokuje

6.2) Vylepšení nákupu předmětů: Zadám, že poptávám X itemů a systém seřadí itemy dle výhodnosti a podbarví to xy řádek a předvyplní počet kusů a nahoře zobrazí tlačítko Koupit vybrané
- případně zobrazit kolik itemů chybí

7) Žebříček obchodníků s největšími obraty (sloupce: nick (i obrázek hlavy), první nabídka v aukci (nebo registrace hesla do aukce), celkový obrat, celkový zisk?, počet koupených aukcí, počet vytvořených aukcí

8) Nabídky neprodané déle, než KONSTANTA přesunout do virtuálního inventáře a při přihlášení do hry zobrazit hlášení o zrušené aukci

9) Logování
- přihlašování na web/odhlašování?
- vytvoření nabídky (i podrobnosti)
- nákup itemů (i podrobnosti)
- info o úspěšném prodeji itemů
- zrušené aukce

10) Potvrzování nákupů javascriptem

11) ADMIN PANEL
- podle permicí ve hře + staticky UUID Sekiphp, Sognus :+1: 
- možnost nastavení maximální ceny pro každý item
- možnost zrušit manuálně aukci - suroviny se vrátí majiteli

12) seznam všech aukčních bodů (vyhledej mi nejbližší aukci - příkazem ve hře)

13) Dražení enchantovaných a výjimečných itemů

14) Vizuální a ostatní
- podbarvení pozadí dle příznivosti ceny?
- našeptávání bloků při vyhledávání s ikonkami?
- seznam všech itemů s obrázky
- přehled všech bloků s číslem indikujícím počet aukcí daného itemu (aby hráč věděl po čem je poptávka a po čem není, popřípadě co je nabízeno a co není)

Poznámka: U prodeje cena itemu max o X procent vyšší než aktuální nejlevnější cena daného itemu

**Comment by DvnBthlo** [comment]
Souhlasím :+1:

**Comment by Sekiphp** [comment]
Aktualizováno a přidány nové body a podbody

**Comment by Sognus** [comment]
Moved to proper repository: https://github.com/Sekiphp/MineAuction
